In [1]:
import requests
import openpyxl
import pandas as pd
import numpy as np
import mysql.connector
import matplotlib.pyplot as plt
from mysql.connector import Error
from sqlalchemy import create_engine

In [2]:
# Function to connect to MySQL using SQLAlchemy + mysql-connector
def connect_to_mysql_sqlalchemy(user, password, host='localhost', database=None):
    """
    Establishes a connection to a MySQL database using SQLAlchemy with mysql-connector as the driver.

    Parameters:
        user (str): Username for MySQL (e.g., 'root')
        password (str): Password for the MySQL user
        host (str): Hostname or IP address (default = 'localhost')
        database (str): Name of the MySQL database/schema to connect to

    Returns:
        engine: A SQLAlchemy engine object if successful, or None if connection fails
    """

    try:
        # Check if a database name was provided; raise error if not
        if not database:
            raise ValueError("Database name must be provided")

        # Construct the SQLAlchemy connection string
        # Format: "dialect+driver://username:password@host/database"
        connection_string = f"mysql+mysqlconnector://{user}:{password}@{host}/{database}"

        # Create the SQLAlchemy engine object using the connection string
        engine = create_engine(connection_string)

        # Test the connection by opening it briefly
        with engine.connect() as conn:
            print("Connected to MySQL via SQLAlchemy successfully")

        # Return the engine so you can use it for reading/writing/querying
        return engine

    except Exception as e:
        # If there's any error (e.g., wrong credentials or DB doesn't exist), print and return None
        print("Failed to connect:", e)
        return None

In [3]:
# Connect to MySQL with "job application" database
engine = connect_to_mysql_sqlalchemy('root', 'Poloniasi28~', database='job application')

Connected to MySQL via SQLAlchemy successfully

In [4]:
# A function for data exploration, including data preview, description, and missing values
def data_preview(df):
    print("Data Preview:")
    print(df.head())
    print("\nData Description:")
    print(df.describe())
    print("\nData Info:")
    print(df.info())
    print("\nMissing Values:")
    print(df.isnull().sum())
    print("\nData Types:")
    print(df.dtypes)
    print("\nUnique Values in Each Column:")
    for col in df.columns:
        print(f"{col}: {df[col].nunique()} unique values")

In [5]:
# This function cleans the data by removing duplicates and converting date columns to datetime
# and stripping whitespace from string columns
def clean_data(df):
    df = df.drop_duplicates()
    
    first_col = df.columns[0]
    if df[first_col].dtype == 'object':
        df[first_col] = pd.to_datetime(df[first_col], errors='coerce', dayfirst=True)

    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].str.strip()

    return df

In [6]:
# Reads the Excel file and loads the data into a DataFrame
df = pd.read_excel("C:/Resumes & Cover Letters/Job Applications.xlsx", sheet_name="Sheet1")
# Display the data preview
data_preview(df)
# Clean the data
clean_data(df)

Data Preview:
  Date Applied     Industry                             Company      Level  \
0   2024-04-09   Technology                             Trideca      Entry
1   2024-06-18  Recruitment                   Alzaro Consulting  Mid-Level
2   2024-06-18  Recruitment  Professional Recruitment Australia  Mid-Level
3   2024-06-25      Finance   McMillan Shakespeare Group (MMSG)  Mid-Level
4   2024-07-03  Recruitment                                 IAG  Mid-Level

       Role/Position            Location Application Source   Job Type  \
0       Data Analyst      Melbourne, VIC             Indeed  Full-Time
1       Data Analyst  Hawthorn East, VIC               Seek  Full-Time
2       Data Analyst      Melbourne, VIC             Indeed  Full-Time
3       Data Analyst      Melbourne, VIC             Indeed  Full-Time
4  Reporting Analyst      Melbourne, VIC               Seek  Full-Time

    Outcome  Interview Date  Skills  Notes
0  Rejected             NaN     NaN    NaN
1   Pending             NaN     NaN    NaN
2   Pending             NaN     NaN    NaN
3  Rejected             NaN     NaN    NaN
4   Pending             NaN     NaN    NaN

Data Description:
                        Date Applied  Interview Date  Skills  Notes
count                             51             0.0     0.0    0.0
mean   2024-10-24 22:07:03.529411840             NaN     NaN    NaN
min              2024-04-09 00:00:00             NaN     NaN    NaN
25%              2024-07-17 12:00:00             NaN     NaN    NaN
50%              2024-09-18 00:00:00             NaN     NaN    NaN
75%              2025-03-24 00:00:00             NaN     NaN    NaN
max              2025-05-02 00:00:00             NaN     NaN    NaN
std                              NaN             NaN     NaN    NaN

Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date Applied        51 non-null     datetime64[ns]
 1   Industry            51 non-null     object
 2   Company             51 non-null     object
 3   Level               51 non-null     object
 4   Role/Position       51 non-null     object
 5   Location            51 non-null     object
 6   Application Source  51 non-null     object
 7   Job Type            51 non-null     object
 8   Outcome             51 non-null     object
 9   Interview Date      0 non-null      float64
 10  Skills              0 non-null      float64
 11  Notes               0 non-null      float64
dtypes: datetime64[ns](1), float64(3), object(8)
memory usage: 4.9+ KB
None

Missing Values:
Date Applied           0
Industry               0
Company                0
Level                  0
Role/Position          0
Location               0
Application Source     0
Job Type               0
Outcome                0
Interview Date        51
Skills                51
Notes                 51
dtype: int64

Data Types:
Date Applied          datetime64[ns]
Industry                      object
Company                       object
Level                         object
Role/Position                 object
Location                      object
Application Source            object
Job Type                      object
Outcome                       object
Interview Date               float64
Skills                       float64
Notes                        float64
dtype: object

Unique Values in Each Column:
Date Applied: 30 unique values
Industry: 12 unique values
Company: 50 unique values
Level: 3 unique values
Role/Position: 8 unique values
Location: 8 unique values
Application Source: 5 unique values
Job Type: 2 unique values
Outcome: 3 unique values
Interview Date: 0 unique values
Skills: 0 unique values
Notes: 0 unique values

,Date Applied,Industry,Company,Level,Role/Position,Location,Application Source,Job Type,Outcome,Interview Date,Skills,Notes
0,2024-04-09,Technology,Trideca,Entry,Data Analyst,"Melbourne, VIC",Indeed,Full-Time,Rejected,NaN,NaN,NaN
1,2024-06-18,Recruitment,Alzaro Consulting,Mid-Level,Data Analyst,"Hawthorn East, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
2,2024-06-18,Recruitment,Professional Recruitment Australia,Mid-Level,Data Analyst,"Melbourne, VIC",Indeed,Full-Time,Pending,NaN,NaN,NaN
3,2024-06-25,Finance,McMillan Shakespeare Group (MMSG),Mid-Level,Data Analyst,"Melbourne, VIC",Indeed,Full-Time,Rejected,NaN,NaN,NaN
4,2024-07-03,Recruitment,IAG,Mid-Level,Reporting Analyst,"Melbourne, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
5,2024-07-04,Technology,MYOB,Mid-Level,Data Analyst,"Melbourne, VIC",Indeed,Full-Time,Rejected,NaN,NaN,NaN
6,2024-07-05,Real Estate,Equiem,Mid-Level,Data Analyst,"Melbourne, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
7,2024-07-08,Technology,Velrada,Entry,Business Analyst,"Melbourne, VIC",Referral,Full-Time,Rejected,NaN,NaN,NaN
8,2024-07-09,Transportation,Transurban,Entry,Reporting Analyst,"Melbourne, VIC",Indeed,Full-Time,Rejected,NaN,NaN,NaN
9,2024-07-15,Recruitment,Bluefin Resources Pty Limited,Mid-Level,Data Analyst,"Melbourne, VIC",Seek,Full-Time,Rejected,NaN,NaN,NaN
10,2024-07-15,Technology,Culture Amp,Mid-Level,Data Analyst,"Melbourne, VIC",Indeed,Full-Time,Rejected,NaN,NaN,NaN
11,2024-07-15,Finance,Redowl Ai,Intern,Business Analyst,"Melbourne, VIC",Referral,Part-Time,Accepted,NaN,NaN,NaN
12,2024-07-17,Recruitment,SMC Executive,Mid-Level,Data Analyst,"Melbourne, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
13,2024-07-18,Investment,Complete AMS,Mid-Level,Data Analyst,"Melbourne, VIC",Linkedin,Full-Time,Rejected,NaN,NaN,NaN
14,2024-08-02,Investment,Warakirri Asset Management,Mid-Level,Data Analyst,"Melbourne, VIC",Indeed,Full-Time,Rejected,NaN,NaN,NaN
15,2024-09-03,Real Estate,Forum Recruitment,Entry,Property Analyst,"Melbourne, VIC",Seek,Full-Time,Rejected,NaN,NaN,NaN
16,2024-09-03,Recruitment,Proforce,Entry,Data Analyst,"Melbourne, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
17,2024-09-04,Technology,DXC Technology,Mid-Level,Administration,"Melbourne, VIC",Indeed,Full-Time,Pending,NaN,NaN,NaN
18,2024-09-05,Health,Saint John of God Healthcare,Mid-Level,Data Analyst,"Melbourne, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
19,2024-09-05,Investment,Realm Investment House,Entry,Data Analyst,"Melbourne, VIC",Linkedin,Full-Time,Pending,NaN,NaN,NaN
20,2024-09-05,Recruitment,Symmetry Human Resource,Mid-Level,Data Analyst,"Melbourne, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
21,2024-09-05,Recruitment,Aurec Group,Entry,Data Analyst,"Melbourne, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
22,2024-09-17,Recruitment,Jenny Barbour,Entry,Data Analyst,"South Yarra, VIC",Indeed,Full-Time,Pending,NaN,NaN,NaN
23,2024-09-17,Recruitment,Hays,Mid-Level,Business Analyst,"Melbourne, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
24,2024-09-18,Health,Austin Health,Entry,Data Analyst,"Heidelberg, VIC",Indeed,Full-Time,Pending,NaN,NaN,NaN
25,2024-09-18,Marketing,Adcorp Group,Mid-Level,Data Analyst,"Melbourne, VIC",Indeed,Full-Time,Pending,NaN,NaN,NaN
26,2024-09-18,Recruitment,Paxus,Mid-Level,Data Analyst,"Melbourne, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
27,2024-09-18,Recruitment,Recruitment Hive,Mid-Level,Data Analyst,"Melbourne, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
28,2024-09-19,Finance,Atlas Partners,Entry,Data Analyst,"Melbourne, VIC",Indeed,Full-Time,Pending,NaN,NaN,NaN
29,2024-09-19,Finance,IQ Group,Entry,Business Consultant,"Melbourne, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
30,2024-09-20,Marketing,Creative Activation,Mid-Level,Business Development Manager,"Melbourne, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
31,2024-09-24,Finance,Liberty Financial,Mid-Level,Business Consultant,"Melbourne, VIC",Seek,Full-Time,Pending,NaN,NaN,NaN
32,2024-09-24,Recruitment,Study and Work,Intern,Data Analyst,"Melbourne, VIC",Jora,Full-Time,Pending,NaN,NaN,NaN
33,2024-09-25,Recruitment,Give A Grad A Go,Entry,IT Service Delivery,"Abbotsford, VIC",Indeed,Full-Time,Rejected,NaN,NaN,NaN
34,2024-09-27,Recruitment,Davidson,Entry,Business Analyst,"Melbourne, VIC",Seek,Full-Time,Rejected,NaN,NaN,NaN
35,2024-10-07,Technology,Culture Amp,Entry,Data Analyst,"Melbourne, VIC",Indeed,Full-Time,Rejected,NaN,NaN,NaN
36,2024-10-28,Recruitment,StraightUp Consulting,Intern,Data Analyst,"Cremorne, VIC",Referral,Part-Time,Accepted,NaN,NaN,NaN
37,2025-03-13,NFP,Anglicare Victoria,Intern,Data Analyst,"Collingwood, VIC",Referral,Part-Time,Accepted,NaN,NaN,NaN
38,2025-04-04,Retail,Country Road,Mid-Level,Data Analyst,"Melbourne, VIC",Linkedin,Full-Time,Rejected,NaN,NaN,NaN
39,2025-04-17,Technology,Programa,Mid-Level,Data Analyst,"Melbourne, VIC",Linkedin,Full-Time,Pending,NaN,NaN,NaN
40,2025-04-29,Real Estate,JLL,Mid-Level,Business Analyst,"Melbourne, VIC",Linkedin,Full-Time,Pending,NaN,NaN,NaN
41,2025-04-29,Finance,Pepperstone,Mid-Level,Data Analyst,"Melbourne, VIC",Linkedin,Full-Time,Pending,NaN,NaN,NaN
42,2025-05-01,NFP,Epworth,Mid-Level,Business Analyst,"Hawthorn, VIC",Linkedin,Full-Time,Rejected,NaN,NaN,NaN
43,2025-05-01,Finance,Eightcap,Mid-Level,Business Analyst,"Melbourne, VIC",Linkedin,Full-Time,Pending,NaN,NaN,NaN
44,2025-05-01,Manufacturing,OEC,Entry,Data Analyst,"Melbourne, VIC",Linkedin,Full-Time,Pending,NaN,NaN,NaN
45,2025-05-01,Finance,InComm Payments,Mid-Level,Data Analyst,"Melbourne, VIC",Linkedin,Full-Time,Pending,NaN,NaN,NaN
46,2025-05-01,Utility,Intellihub,Mid-Level,Reporting Analyst,"Melbourne, VIC",Linkedin,Full-Time,Pending,NaN,NaN,NaN
47,2025-05-01,Finance,Moula,Entry,Reporting Analyst,"Melbourne, VIC",Linkedin,Full-Time,Pending,NaN,NaN,NaN
48,2025-05-02,Marketing,R/GA,Mid-Level,Data Analyst,"Melbourne, VIC",Linkedin,Full-Time,Pending,NaN,NaN,NaN
49,2025-05-02,Finance,Empower Finance,Mid-Level,Data Analyst,"Melbourne, VIC",Linkedin,Full-Time,Pending,NaN,NaN,NaN
50,2025-05-02,Finance,Netwealth,Mid-Level,Data Analyst,"Melbourne, VIC",Linkedin,Full-Time,Rejected,NaN,NaN,NaN

In [7]:
# Filter the DataFrame to exclude the last three columns
# Assuming the last three columns are not needed for analysis
df_filtered = df.iloc[:, :-3]
# Store the filtered DataFrame into a MySQL table
# The table name is "job applications"
df_filtered.to_sql(name = "job applications", con = engine, if_exists = "replace", index = False)

51